# Generated by Django 4.0.3 on 2022-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SU', 'Surrounds'), ('IN', 'Inserts'), ('HE', 'Hearths'), ('PA', 'Parts')], default='PA', max_length=10),
        ),
    ]
